---
title: README -- John Hopkins University -- Data Science Specialization -- Statistical
  Inference Course -- Course Project
author: "Dr. Guy Cohen"
date: "July 21, 2015"
output: pdf_document
---

## Overview for part 1

In this project you will investigate the exponential distribution in R and compare it with the Central Limit Theorem. The exponential distribution can be simulated in R with rexp(n, lambda) where $\lambda$ is the rate parameter. The mean of exponential distribution is $1/\lambda$ and the standard deviation is also $1/\lambda$. Set $\lambda= 0.2$ for all of the simulations. You will investigate the distribution of averages of 40 exponentials. Note that you will need to do a thousand simulations.

Illustrate via simulation and associated explanatory text the properties of the distribution of the mean of 40 exponentials.  You should  
1. Show the sample mean and compare it to the theoretical mean of the distribution.  
2. Show how variable the sample is (via variance) and compare it to the theoretical variance of the distribution.  
3. Show that the distribution is approximately normal.  

## Overview for part 2

In this part, you are going to analyze the ToothGrowth data in the R datasets package.

1. Load the ToothGrowth data, and perform some basic exploratory data analyses.  
2. Provide a basic summary of the data.  
3. Use confidence intervals and/or hypothesis tests to compare tooth growth by supp and dose. (Only use the techniques from class, even if there's other approaches worth considering).  
4. State your conclusions and the assumptions needed for your conclusions. 

## Description of Dataset for part 2

The dataset is titled "The Effect of Vitamin C on Tooth Growth in Guinea Pigs." The dataset is given as a data frame with 60 observations on 3 variables:

[,1] len (numeric) -- Tooth length  
[,2] supp (factor) -- Supplement type (VC or OJ)  
[,3] dose (numeric) -- Dose in milligrams

The response is the length of odontoblasts (teeth) in each of 10 guinea pigs at each of three dose levels of Vitamin C (0.5, 1, and 2 mg) with each of two delivery methods (orange juice or ascorbic acid).
